<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/05/03 14:51:07
sfConfig::add(array(
  'app_tag_max_lovers' => 10,
  'app_csrf' => 'berkin10caro',
  'app_friend_request' => array (
  0 => 'pending',
  1 => 'accepted',
  2 => 'blocked',
),
));
