<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/05/03 14:51:07
sfConfig::add(array(
  'sf_i18n_default_culture' => 'tr_TR',
  'sf_i18n_source' => 'XLIFF',
  'sf_i18n_debug' => false,
  'sf_i18n_cache' => true,
  'sf_i18n_untranslated_prefix' => '[T]',
  'sf_i18n_untranslated_suffix' => '[/T]',
));
