<?php
// auto-generated by sfSecurityConfigHandler
// date: 2009/10/19 00:28:01
$this->security = array (
  'love' => 
  array (
    'is_secure' => true,
    'credentials' => 'subscriber',
  ),
  'upload' => 
  array (
    'is_secure' => true,
    'credentials' => 'subscriber',
  ),
  'profile' => 
  array (
    'is_secure' => true,
    'credentials' => 'subscriber',
  ),
  'pictureremove' => 
  array (
    'is_secure' => true,
    'credentials' => 'subscriber',
  ),
  'picturesetavatar' => 
  array (
    'is_secure' => true,
    'credentials' => 'subscriber',
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
