<?php
// auto-generated by sfValidatorConfigHandler
// date: 2009/10/19 01:04:37

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validators['nicknameValidator'] = new sfStringValidator();
  $validators['nicknameValidator']->initialize($context, array (
  'min' => 5,
  'min_error' => 'Kullanıcı adınız en az 5 karakter olmalı.',
));
  $validators['userValidator'] = new myLoginValidator();
  $validators['userValidator']->initialize($context, array (
  'remember' => 'remember',
  'password' => 'password',
  'login_error' => 'Kullanıcı adı veya şifre hatalı.',
));
  $validatorManager->registerName('nickname', 1, 'Kullanıcı adınızı girmeniz gerekiyor.', null, null, false);
  $validatorManager->registerValidator('nickname', $validators['nicknameValidator'], null);
  $validatorManager->registerValidator('nickname', $validators['userValidator'], null);
  $validatorManager->registerName('password', 1, 'Şifrenizi girmeniz gerekiyor.', null, null, false);
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
