<?php
// auto-generated by sfValidatorConfigHandler
// date: 2009/10/19 00:26:22

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validators['userValidator'] = new sfCallbackValidator();
  $validators['userValidator']->initialize($context, array (
  'callback' => 
  array (
    0 => 'UserPeer',
    1 => 'checkUser',
  ),
  'invalid_error' => 'Kullanıcı bulunamadı.',
));
  $validators['schizoidValidator'] = new sfCallbackValidator();
  $validators['schizoidValidator']->initialize($context, array (
  'callback' => 
  array (
    0 => 'myTools',
    1 => 'checkSchizoid',
  ),
  'invalid_error' => 'Kendinize mesaj atamazsınız.',
));
  $validators['titleValidator'] = new sfStringValidator();
  $validators['titleValidator']->initialize($context, array (
  'max' => 255,
  'max_error' => '255 characters max',
));
  $validatorManager->registerName('recipent', 1, 'Mesaj göndereceğiniz kişinin kullanıcı adını girmeniz gerekli.', null, null, false);
  $validatorManager->registerValidator('recipent', $validators['userValidator'], null);
  $validatorManager->registerValidator('recipent', $validators['schizoidValidator'], null);
  $validatorManager->registerName('title', 0, 'required', null, null, false);
  $validatorManager->registerValidator('title', $validators['titleValidator'], null);
  $validatorManager->registerName('body', 1, 'Mesajınızı boş bırakamazsınız.', null, null, false);
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
