<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/10/19 00:26:31
sfConfig::add(array(
  'sf_mailer_'.strtolower($moduleName).'_deliver' => true,
  'sf_mailer_'.strtolower($moduleName).'_mailer' => 'sendmail',
  'sf_mailer_'.strtolower($moduleName).'_domain' => 'localhost.localdomain',
  'sf_mailer_'.strtolower($moduleName).'_hostname' => 'localhost',
  'sf_mailer_'.strtolower($moduleName).'_port' => 25,
  'sf_mailer_'.strtolower($moduleName).'_username' => '',
  'sf_mailer_'.strtolower($moduleName).'_password' => '',
  'sf_mailer_'.strtolower($moduleName).'_wordwrap' => 80,
  'sf_mailer_'.strtolower($moduleName).'_priority' => 3,
  'sf_mailer_'.strtolower($moduleName).'_content_type' => 'text/plain',
  'sf_mailer_'.strtolower($moduleName).'_charset' => 'utf-8',
  'sf_mailer_'.strtolower($moduleName).'_encoding' => '8bit',
));
