# default rules
homepage:
  url:   /
  param: { module: tag, action: index }

register:
  url:    /uye-ol/*
  param: { module: user, action: register }

login:
  url:    /giris/*
  param: { module: user, action: login }

logout:
  url:    /cikis/*
  param: { module: user, action: logout }

tag_add:
  url:    /tag/add/*
  param:  { module: tag, action: add }

tag_search:
  url:    /tag/search/*
  param:  { module: tag, action: search }

tag:
  url:    /etiket/:stripped_tag/:page
  param:  { module: tag, action: show, page: 1 }
  requirements: { page: \d+ }

tag_lovers:
  url:    /etiket/:stripped_tag/:sense/:page
  param:  { module: tag, action: lovers, page: 1 }

add_comment:
  url:    /comment/add/*
  param:  { module: comment, action: add }

user_pictures:
  url:    /uye/:nick/resimler/*
  param:  { module: user, action: picture }
  
user_picture_delete:
  url:    /resim-sil/:id
  param:  { module: user, action: pictureRemove }
  
user_picture_avatar:
  url:    /avatar/:id
  param:  { module: user, action: pictureSetAvatar }

  
user_profile:
  url:    /uye/:nick/*
  param:  { module: user, action: show }

user_edit_profile:
  url:    /uye/:nick/profil/*
  param:  { module: user, action: profile }
  
user_love:
  url:    /seviyor-mu/*
  param:  { module: user, action: love }
  
user_upload:
  url:    /resim-yukle/*
  param:  { module: user, action: upload }
  
user_tags:
  url:    /uye/:nick/tags/:sense/*
  param:  { module: user, action: tags, sense: all, display: true }

user_notr:
  url:    /uye/notr/*
  param:  { module: user, action: notr }
  
user_password_request:
  url:    /sifremi-unuttum/*
  param:  { module: user, action: passwordRequest }

friends:
  url:    /friends/*
  param:  { module: friend, action: list }

friend_request:
  url:    /friend/add/*
  param:  { module: friend, action: add }

friend_request_list:
  url:    /friend/requests/*
  param:  { module: friend, action: request }

friend_remove:
  url:    /friend/remove/*
  param:  { module: friend, action: remove }
  
conversations:
  url:    /mailbox/:folder/*
  param:  { module: conversation, action: index, folder: inbox, display: true }
  
conversation_read:
  url:    /mail/read/*
  param:  { module: conversation, action: read }
  
conversation_compose:
  url:    /mail/compose/*
  param:  { module: conversation, action: compose }

conversation_reply:
  url:    /mail/reply/*
  param:  { module: conversation, action: reply }
  
conversation_remove:
  url:    /mail/remove/*
  param:  { module: conversation, action: remove }
  
messages:
  url:    /messages/*
  param:  { module: message, action: index }

message_read:
  url:    /message/read/*
  param:  { module: message, action: read }

message_add:
  url:    /message/new/*
  param:  { module: message, action: add }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
