default:
  http_metas:
    content-type: text/html

  metas:
    title:        kuyabiye.com
    robots:       index, follow
    description:  Sevdiðin sevmediðin herþeyi profiline ekle, arkadaþlarýnla paylaþ!
    keywords:     kuyabiye, arkadaþlýk, sosyal að, seviyor, sevmiyor
    language:     tr

  stylesheets:    [default]

  javascripts:    []

  has_layout:     on
  layout:         layout
