love:
  is_secure: on
  credentials: subscriber

upload:
  is_secure: on
  credentials: subscriber

profile:
  is_secure: on
  credentials: subscriber
  
pictureRemove:
  is_secure: on
  credentials: subscriber
  
pictureSetAvatar:
  is_secure: on
  credentials: subscriber
  
# all:
  # is_secure: off