love:
  is_secure: on
  credentials: subscriber

upload:
  is_secure: on
  credentials: subscriber

profile:
  is_secure: on
  credentials: subscriber
  
pictureRemove:
  is_secure: on
  credentials: subscriber
  
pictureSetAvatar:
  is_secure: on
  credentials: subscriber

facebook:
  is_secure: on
  credentials: subscriber
  
userEdit:
  is_secure: on
  credentials: subscriber
  
facebookSettings:
  is_secure: on
  credentials: subscriber  

  
# all:
  # is_secure: off