methods:
  post: [recipent, title, body]

names:
  recipent:
    required:     true
    required_msg: required
    validators:   [userValidator, schizoidValidator]
  
  title:
    required:     true
    required_msg: required
    validators:   [titleValidator]

  body:
    required:     true
    required_msg: required
  
userValidator:
  class:          sfCallbackValidator
  param:
    callback:       [UserPeer, checkUser]
    invalid_error:  user is not found

schizoidValidator:
  class:          sfCallbackValidator
  param:
    callback:       [myTools, checkSchizoid]
    invalid_error:  you cant send message to yourself

titleValidator:
  class:            sfStringValidator
  param:
    max:            255
    max_error:      255 characters max
