methods:
  post: [recipent, title, body]

names:
  recipent:
    required:     true
    required_msg:  Mesaj göndereceğiniz kişinin kullanıcı adını girmeniz gerekli.
    validators:   [userValidator, schizoidValidator]
  
  title:
    required:     false
    required_msg: required
    validators:   [titleValidator]

  body:
    required:     true
    required_msg: Mesajınızı boş bırakamazsınız.
  
userValidator:
  class:          sfCallbackValidator
  param:
    callback:       [UserPeer, checkUser]
    invalid_error:  Kullanıcı bulunamadı.

schizoidValidator:
  class:          sfCallbackValidator
  param:
    callback:       [myTools, checkSchizoid]
    invalid_error:  Kendinize mesaj atamazsınız.

titleValidator:
  class:            sfStringValidator
  param:
    max:            255
    max_error:      255 characters max
