prod:
  propel:
    class:    sfPropelDatabase
    param:
      phptype:  mysql
      host:     localhost
      database: kuyabiye
      username: xxxxx
      password: xxxxx
      encoding: utf8

all:
  propel:
    class:      sfPropelDatabase
    param:
      phptype:  mysql
      host:     localhost
      database: kuyabiye
      username: xxxxx
      password: xxxxx
      encoding: utf8

