<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/01/21 00:54:05

$database = new sfPropelDatabase();
$database->initialize(array (
  'phptype' => 'mysql',
  'host' => 'localhost',
  'database' => 'kuyabiye',
  'username' => 'root',
  'password' => 32141809,
  'encoding' => 'utf8',
), 'propel');
$this->databases['propel'] = $database;
