<?php
// auto-generated by sfRoutingConfigHandler
// date: 2009/10/19 01:29:35
$routes = sfRouting::getInstance();
$routes->setRoutes(
array (
  'homepage' => 
  array (
    0 => '/',
    1 => '/^[\\/]*$/',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'tag',
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'register' => 
  array (
    0 => '/uye-ol/*',
    1 => '#^/uye-ol(?:\\/(.*))?$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'user',
      'action' => 'register',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'login' => 
  array (
    0 => '/giris/*',
    1 => '#^/giris(?:\\/(.*))?$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'user',
      'action' => 'login',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'logout' => 
  array (
    0 => '/cikis/*',
    1 => '#^/cikis(?:\\/(.*))?$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'user',
      'action' => 'logout',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'tag_add' => 
  array (
    0 => '/tag/add/*',
    1 => '#^/tag/add(?:\\/(.*))?$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'tag',
      'action' => 'add',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'tag_search' => 
  array (
    0 => '/tag/search/*',
    1 => '#^/tag/search(?:\\/(.*))?$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'tag',
      'action' => 'search',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'tag' => 
  array (
    0 => '/etiket/:stripped_tag/:page',
    1 => '#^/etiket(?:\\/([^\\/]+))?(?:\\/(\\d+))?$#',
    2 => 
    array (
      0 => 'stripped_tag',
      1 => 'page',
    ),
    3 => 
    array (
      'stripped_tag' => 1,
      'page' => 1,
    ),
    4 => 
    array (
      'module' => 'tag',
      'action' => 'show',
      'page' => 1,
    ),
    5 => 
    array (
      'page' => '\\d+',
    ),
    6 => '',
  ),
  'tag_lovers' => 
  array (
    0 => '/etiket/:stripped_tag/:sense/:page',
    1 => '#^/etiket(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'stripped_tag',
      1 => 'sense',
      2 => 'page',
    ),
    3 => 
    array (
      'stripped_tag' => 1,
      'sense' => 1,
      'page' => 1,
    ),
    4 => 
    array (
      'module' => 'tag',
      'action' => 'lovers',
      'page' => 1,
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'add_comment' => 
  array (
    0 => '/comment/add/*',
    1 => '#^/comment/add(?:\\/(.*))?$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'comment',
      'action' => 'add',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'user_pictures' => 
  array (
    0 => '/uye/:nick/resimler/*',
    1 => '#^/uye(?:\\/([^\\/]+))?/resimler(?:\\/(.*))?$#',
    2 => 
    array (
      0 => 'nick',
    ),
    3 => 
    array (
      'nick' => 1,
    ),
    4 => 
    array (
      'module' => 'user',
      'action' => 'picture',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'user_picture_delete' => 
  array (
    0 => '/resim-sil/:id',
    1 => '#^/resim-sil(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'id',
    ),
    3 => 
    array (
      'id' => 1,
    ),
    4 => 
    array (
      'module' => 'user',
      'action' => 'pictureRemove',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'user_picture_avatar' => 
  array (
    0 => '/avatar/:id',
    1 => '#^/avatar(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'id',
    ),
    3 => 
    array (
      'id' => 1,
    ),
    4 => 
    array (
      'module' => 'user',
      'action' => 'pictureSetAvatar',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'user_profile' => 
  array (
    0 => '/uye/:nick',
    1 => '#^/uye(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'nick',
    ),
    3 => 
    array (
      'nick' => 1,
    ),
    4 => 
    array (
      'module' => 'user',
      'action' => 'show',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'user_edit_profile' => 
  array (
    0 => '/hesabim/*',
    1 => '#^/hesabim(?:\\/(.*))?$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'user',
      'action' => 'profile',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'user_love' => 
  array (
    0 => '/seviyor-musun/*',
    1 => '#^/seviyor-musun(?:\\/(.*))?$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'user',
      'action' => 'love',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'user_upload' => 
  array (
    0 => '/resim-yukle/*',
    1 => '#^/resim-yukle(?:\\/(.*))?$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'user',
      'action' => 'upload',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'user_tags' => 
  array (
    0 => '/uye/:nick/:sense/:page',
    1 => '#^/uye(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?(?:\\/(\\d+))?$#',
    2 => 
    array (
      0 => 'nick',
      1 => 'sense',
      2 => 'page',
    ),
    3 => 
    array (
      'nick' => 1,
      'sense' => 1,
      'page' => 1,
    ),
    4 => 
    array (
      'module' => 'user',
      'action' => 'tags',
      'page' => 1,
    ),
    5 => 
    array (
      'page' => '\\d+',
    ),
    6 => '',
  ),
  'user_notr' => 
  array (
    0 => '/uye/notr/*',
    1 => '#^/uye/notr(?:\\/(.*))?$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'user',
      'action' => 'notr',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'user_password_request' => 
  array (
    0 => '/sifremi-unuttum/*',
    1 => '#^/sifremi-unuttum(?:\\/(.*))?$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'user',
      'action' => 'passwordRequest',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'friends' => 
  array (
    0 => '/friends/*',
    1 => '#^/friends(?:\\/(.*))?$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'friend',
      'action' => 'list',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'friend_request' => 
  array (
    0 => '/friend/add/*',
    1 => '#^/friend/add(?:\\/(.*))?$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'friend',
      'action' => 'add',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'friend_request_list' => 
  array (
    0 => '/friend/requests/*',
    1 => '#^/friend/requests(?:\\/(.*))?$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'friend',
      'action' => 'request',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'friend_remove' => 
  array (
    0 => '/friend/remove/*',
    1 => '#^/friend/remove(?:\\/(.*))?$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'friend',
      'action' => 'remove',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'conversations' => 
  array (
    0 => '/mesajlar/:folder/:page',
    1 => '#^/mesajlar(?:\\/([^\\/]+))?(?:\\/(\\d+))?$#',
    2 => 
    array (
      0 => 'folder',
      1 => 'page',
    ),
    3 => 
    array (
      'folder' => 1,
      'page' => 1,
    ),
    4 => 
    array (
      'module' => 'conversation',
      'action' => 'index',
      'folder' => 'gelen',
      'display' => true,
      'page' => 1,
    ),
    5 => 
    array (
      'page' => '\\d+',
    ),
    6 => '',
  ),
  'conversation_read' => 
  array (
    0 => '/mesaj/oku/:id/*',
    1 => '#^/mesaj/oku(?:\\/([^\\/]+))?(?:\\/(.*))?$#',
    2 => 
    array (
      0 => 'id',
    ),
    3 => 
    array (
      'id' => 1,
    ),
    4 => 
    array (
      'module' => 'conversation',
      'action' => 'read',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'conversation_compose' => 
  array (
    0 => '/mesaj/yaz/:recipent/*',
    1 => '#^/mesaj/yaz(?:\\/([^\\/]+))?(?:\\/(.*))?$#',
    2 => 
    array (
      0 => 'recipent',
    ),
    3 => 
    array (
      'recipent' => 1,
    ),
    4 => 
    array (
      'module' => 'conversation',
      'action' => 'compose',
      'recipent' => ' ',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'conversation_reply' => 
  array (
    0 => '/mesaj/cevap/*',
    1 => '#^/mesaj/cevap(?:\\/(.*))?$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'conversation',
      'action' => 'reply',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'conversation_remove' => 
  array (
    0 => '/mesaj/sil/*',
    1 => '#^/mesaj/sil(?:\\/(.*))?$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'conversation',
      'action' => 'remove',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'messages' => 
  array (
    0 => '/messages/*',
    1 => '#^/messages(?:\\/(.*))?$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'message',
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'message_read' => 
  array (
    0 => '/message/read/*',
    1 => '#^/message/read(?:\\/(.*))?$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'message',
      'action' => 'read',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'message_add' => 
  array (
    0 => '/message/new/*',
    1 => '#^/message/new(?:\\/(.*))?$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'message',
      'action' => 'add',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'default_symfony' => 
  array (
    0 => '/symfony/:action/*',
    1 => '#^/symfony(?:\\/([^\\/]+))?(?:\\/(.*))?$#',
    2 => 
    array (
      0 => 'action',
    ),
    3 => 
    array (
      'action' => 1,
    ),
    4 => 
    array (
      'module' => 'default',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'default_index' => 
  array (
    0 => '/:module',
    1 => '#^(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'module',
    ),
    3 => 
    array (
      'module' => 1,
    ),
    4 => 
    array (
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'default' => 
  array (
    0 => '/:module/:action/*',
    1 => '#^(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?(?:\\/(.*))?$#',
    2 => 
    array (
      0 => 'module',
      1 => 'action',
    ),
    3 => 
    array (
      'module' => 1,
      'action' => 1,
    ),
    4 => 
    array (
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
)
);
