<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/01/13 21:57:37
sfConfig::add(array(
  'app_tag_max_lovers' => 10,
  'app_loves' => array (
  0 => 'hates',
  1 => 'loves',
),
));
