<?php
// auto-generated by sfValidatorConfigHandler
// date: 2009/09/06 21:02:52

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validators['emailValidator'] = new sfEmailValidator();
  $validators['emailValidator']->initialize($context, array (
  'email_error' => 'check your email',
));
  $validators['uniqueEmailValidator'] = new sfPropelUniqueValidator();
  $validators['uniqueEmailValidator']->initialize($context, array (
  'class' => 'User',
  'column' => 'email',
  'unique_error' => 'This email already exists. Please choose another one.',
));
  $validators['passwordValidator'] = new sfCompareValidator();
  $validators['passwordValidator']->initialize($context, array (
  'check' => 'password',
  'compare_error' => 'passwords do not match',
));
  $validators['nameValidator'] = new sfStringValidator();
  $validators['nameValidator']->initialize($context, array (
  'min' => 2,
  'min_error' => '2 characters min',
  'max' => 100,
  'max_error' => '100 characters max',
));
  $validators['dobValidator'] = new sfDateValidator();
  $validators['dobValidator']->initialize($context, array (
  'date_error' => 'not valid date',
));
  $validatorManager->registerName('email', 1, 'required', null, null, false);
  $validatorManager->registerValidator('email', $validators['emailValidator'], null);
  $validatorManager->registerValidator('email', $validators['uniqueEmailValidator'], null);
  $validatorManager->registerName('password', 0, 'required', null, null, false);
  $validatorManager->registerName('repassword', 0, 'required', null, null, false);
  $validatorManager->registerValidator('repassword', $validators['passwordValidator'], null);
  $validatorManager->registerName('firstname', 0, 'Required', null, null, false);
  $validatorManager->registerValidator('firstname', $validators['nameValidator'], null);
  $validatorManager->registerName('lastname', 0, 'Required', null, null, false);
  $validatorManager->registerValidator('lastname', $validators['nameValidator'], null);
  $validatorManager->registerName('dob', 0, 'Required', null, null, false);
  $validatorManager->registerValidator('dob', $validators['dobValidator'], null);
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
