<?php
// auto-generated by sfSecurityConfigHandler
// date: 2009/09/20 13:30:50
$this->security = array (
  'add' => 
  array (
    'is_secure' => true,
    'credentials' => 'subscriber',
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
