<?php
// auto-generated by sfSecurityConfigHandler
// date: 2009/05/03 14:13:22
$this->security = array (
  'love' => 
  array (
    'is_secure' => true,
    'credentials' => 'subscriber',
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
