<?php
// auto-generated by sfSecurityConfigHandler
// date: 2009/09/06 19:12:45
$this->security = array (
  'love' => 
  array (
    'is_secure' => true,
    'credentials' => 'subscriber',
  ),
  'upload' => 
  array (
    'is_secure' => true,
    'credentials' => 'subscriber',
  ),
  'profile' => 
  array (
    'is_secure' => true,
    'credentials' => 'subscriber',
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
