<?php
// auto-generated by sfSecurityConfigHandler
// date: 2009/01/13 22:02:49
$this->security = array (
  'create' => 
  array (
    'is_secure' => true,
    'credentials' => 'subscriber',
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
