<?php
// auto-generated by sfValidatorConfigHandler
// date: 2009/05/03 14:13:22

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validators['nicknameValidator'] = new sfStringValidator();
  $validators['nicknameValidator']->initialize($context, array (
  'min' => 5,
  'min_error' => 'kullanıcı adınız en az 5 karakter olmalı',
));
  $validators['userValidator'] = new myLoginValidator();
  $validators['userValidator']->initialize($context, array (
  'remember' => 'remember',
  'password' => 'password',
  'login_error' => 'kullanıcı adı veya şifre hatalı',
));
  $validatorManager->registerName('nickname', 1, 'kullanıcı adınızı girmeniz gerekiyor', null, null, false);
  $validatorManager->registerValidator('nickname', $validators['nicknameValidator'], null);
  $validatorManager->registerValidator('nickname', $validators['userValidator'], null);
  $validatorManager->registerName('password', 1, 'şifrenizi girmeniz gerekiyor', null, null, false);
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
