<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/01/13 22:16:53
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
