<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/09/06 19:12:45
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
