<?php
// auto-generated by sfValidatorConfigHandler
// date: 2009/09/16 22:18:39

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validators['searchValidator'] = new sfStringValidator();
  $validators['searchValidator']->initialize($context, array (
  'min' => 2,
  'min_error' => 'en az 2 karakter olmalı',
));
  $validatorManager->registerName('search', 1, 'required', null, null, false);
  $validatorManager->registerValidator('search', $validators['searchValidator'], null);
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
