<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/01/21 00:54:05
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
