<?php
// auto-generated by sfPropelCrud
// date: 2009/01/01 18:26:05
?>
      	<div class="tagline">Sevdiğin sevmediğin herşeyi profiline ekle, arkadaşlarınla paylaş!</div>
        
       	<div id="welcome" class="clearfix">
          <div class="tag-flash" id="tag-slideshow">
          <?php foreach ($showcase_tags as $tag): ?>
        	<div class="flash">
            <h2 class="tag"><?php echo link_to($tag, '@tag?stripped_tag=' . $tag->getStrippedTag() . '&page=') ?><small><?php echo link_to($tag->getUser()->getNickname(), '@user_profile?nick=' . $tag->getUser()->getNickname(), array('class' => 'love')) ?> ekledi.</small></h2>
          
            <div class="love-buttons-wrap">
              <ul class="love-buttons">
                <li class="love"><?php echo link_to('Seviyor musun?', '@tag?stripped_tag=' . $tag->getStrippedTag()) ?></li>
                <li class="hate"><?php echo link_to('Sevmiyor musun?', '@tag?stripped_tag=' . $tag->getStrippedTag()) ?></li>
              </ul>
            </div>
            
            <ul class="tag-list">
            	<li><?php echo $tag->getTotal() ?> kişi profiline eklemiş. <span class="love"><?php echo $tag->getLovers() ?></span> kişi seviyor, <span class="hate"><?php echo $tag->getHaters() ?></span> kişi sevmiyor.</li>
            	<li><?php echo $tag->getNbComments() ?> yorum yapılmış.</li>
            	<li><?php echo $tag->getLoverGirls() ?> kadın, <?php echo $tag->getLoverBoys() ?> erkek <span class="love">seviyor.</span></li>
            	<li><?php echo $tag->getHaterGirls() ?> kadın, <?php echo $tag->getHaterBoys() ?> erkek <span class="hate">sevmiyor.</span></li>
            </ul>
      	  </div>
          <?php endforeach; ?>
          </div>
        
          <div class="ad">
           	<a href="#"><?php echo image_tag('ad.jpg') ?></a>
       	  </div>
   	    </div>
        
        <div class="tags">
        	<h2 class="home-header"><a class="love" href="#">bugünlerde sevilenler</a></h2>
          <div class="tag-cloud tag-love">
            <?php foreach ($loved_tags as $tag): ?>
              <?php echo link_to($tag->getTag(), '@tag?stripped_tag=' . $tag->getStrippedTag(), array('class' => 'tag size' . $tag->getWeight())) ?>
            <?php endforeach; ?>
          </div>

          
          <h2 class="home-header"><a class="hate" href="#">bugünlerde sevilmeyenler</a></h2>
          <div class="tag-cloud tag-hate">
            <?php foreach ($hated_tags as $tag): ?>
              <?php echo link_to($tag->getTag(), '@tag?stripped_tag=' . $tag->getStrippedTag(), array('class' => 'tag size' . $tag->getWeight())) ?>
            <?php endforeach; ?>
          </div>
        </div>

        <h2 class="home-header"><a class="love" href="#">son üyeler</a></h2>
				<div class="clearfix">        
        <ul class="users clearfix">
          <?php foreach ( $last_users as $user ) { ?>
        	<li><?php include_partial('user/avatar', array( 'user' => $user )) ?></li>
          <?php } ?>
        </ul>
       	</div>