<?php
// auto-generated by sfPropelCrud
// date: 2009/01/01 18:26:05

use_helper('Date', 'Validation', 'User', 'Pagination');
?>
<h1><?php echo link_to($tag->getTag(), '@tag?stripped_tag=' . $tag->getStrippedTag()); ?><span>(<?php echo link_to($tag->getUser()->getNickname(), '@user_profile?nick=' . $tag->getUser()->getNickname()) ?> ekledi)</span></h1>
<div class="right gray size10"><?php echo time_ago_in_words($tag->getCreatedAt('U')) ?> ago</div>
<div class="tag-actions" id="love_<?php echo $tag->getId() ?>">
  <?php include_partial('love_buttons', array('tag' => $tag)); ?>
</div>
<br />
<h2><?php
switch ( $sense )
{
  case 'lovers':
    echo 'Sevenler';
    break;
  case 'haters':
    echo 'Sevmeyenler';
    break;
  default:
    echo 'Hepsi';
    break;
}

?></h2><br />&nbsp;
<?php echo $users->getNbResults() ?> results found.<br />
<?php if ( $users->getNbResults() ) { ?>
Displaying results <?php echo $users->getFirstIndice() ?> to  <?php echo $users->getLastIndice() ?>.
<?php } ?>
<?php
  $love = sfConfig::get('app_loves');
  foreach ( $users->getResults() as $user )
  {
    
    echo '<div style="float:left">';
    include_partial('user/avatar', array('user' => $user->getUser()));
    echo '<br />' . $user->getUser()->getNickname() . ' ' . $love[$user->getLove()];
    echo '</div>';
  }

?>
<div style="clear:both">&nbsp;</div>
<?php echo pager_navigation($users, '@tag_lovers?stripped_tag=' . $tag->getStrippedTag() . '&sense=' . $sense); ?>
<div style="clear:both">&nbsp;</div>
<?php
  echo link_to('Sevenler', '@tag_lovers?stripped_tag=' . $tag->getStrippedTag() . '&sense=lovers') . ' - ';
  echo link_to('Sevmeyenler', '@tag_lovers?stripped_tag=' . $tag->getStrippedTag() . '&sense=haters') . ' - ';
  echo link_to('Hepsi', '@tag_lovers?stripped_tag=' . $tag->getStrippedTag() . '&sense=all');
  ?>