<?php
// auto-generated by sfPropelCrud
// date: 2009/01/01 18:26:05

use_helper('Date', 'Validation', 'User', 'Pagination');
?>
      	<ul class="breadcrumb"><li class="first"><?php echo link_to('Ana Sayfa', '@homepage') ?></li>::<li><a href="#">Etiketler</a></li>::<li><?php echo link_to($tag, '@tag?stripped_tag=' . $tag->getStrippedTag()); ?> </li></ul>
        
       	<div id="welcome" class="clearfix">
        	<div class="tag-flash">
        		<h2 class="tag"><?php echo link_to($tag, '@tag?stripped_tag=' . $tag->getStrippedTag()) ?><small><?php echo link_to($tag->getUser()->getNickname(), '@user_profile?nick=' . $tag->getUser()->getNickname(), array('class' => 'love')) ?> ekledi.</small></h2>
            <div class="love-buttons-wrap" id="love_<?php echo $tag->getId() ?>">
            <?php include_partial('love_buttons', array('tag' => $tag)); ?>
            </div>
            
            <ul class="tag-list">
            	<li><?php echo $tag->getTotal() ?> kişi profiline eklemiş. <span class="love"><?php echo $tag->getLovers() ?></span> kişi seviyor, <span class="hate"><?php echo $tag->getHaters() ?></span> kişi sevmiyor.</li>
            	<li><?php echo $tag->getNbComments() ?> yorum yapılmış.</li>
            	<li><?php echo $tag->getLoverGirls() ?> kadın, <?php echo $tag->getLoverBoys() ?> erkek <span class="love">seviyor.</span></li>
            	<li><?php echo $tag->getHaterGirls() ?> kadın, <?php echo $tag->getHaterBoys() ?> erkek <span class="hate">sevmiyor.</span></li>
            </ul>
      	  </div>
        
          <div class="ad">
           	<a href="#"><?php echo image_tag('ad.jpg') ?></a>
       	  </div>
   	    </div>
<div class="clearfix">
<h2 class="home-header love"><?php
switch ( $sense )
{
  case 'lovers':
    echo 'Sevenler (' . $users->getNbResults() . ')<small>';
    echo link_to('Sevmeyenler', '@tag_lovers?stripped_tag=' . $tag->getStrippedTag() . '&sense=haters') . ', ';
    echo link_to('Hepsi', '@tag_lovers?stripped_tag=' . $tag->getStrippedTag() . '&sense=all');
    echo '</small>';
    break;
  case 'haters':
    echo 'Sevmeyenler (' . $users->getNbResults() . ')<small>';;
    echo link_to('Sevenler', '@tag_lovers?stripped_tag=' . $tag->getStrippedTag() . '&sense=lovers') . ', ';
    echo link_to('Hepsi', '@tag_lovers?stripped_tag=' . $tag->getStrippedTag() . '&sense=all');
    echo '</small>';
    break;
  default:
    echo 'Hepsi (' . $users->getNbResults() . ')<small>';
    echo link_to('Sevenler', '@tag_lovers?stripped_tag=' . $tag->getStrippedTag() . '&sense=lovers') . ', ';
    echo link_to('Sevmeyenler', '@tag_lovers?stripped_tag=' . $tag->getStrippedTag() . '&sense=haters');
    echo '</small>';
    break;
}

?></h2>
<?php $love = sfConfig::get('app_loves'); ?>
  <ul class="users clearfix">
    <?php foreach ( $users->getResults() as $user ) { ?>
    <li><?php include_partial('user/avatar', array( 'user' => $user->getUser() )) ?><div class="nick"><?php echo $user->getUser()->getNickname() ?></div></li>
    <?php } ?>
  </ul>
</div>
<?php echo pager_navigation($users, '@tag_lovers?stripped_tag=' . $tag->getStrippedTag() . '&sense=' . $sense); ?>
