<?php
// auto-generated by sfPropelCrud
// date: 2009/01/01 18:26:05

use_helper('Date', 'Validation');
?>
<h1><?php echo $search ?></h1>
<div class="tag-actions">
  <span class="lover"><?php echo link_to('seviyor musun?', '@tag_add?loves=1&search=' . $sf_params->get('search')) . ' ' . link_to('sevmiyor musun?', '@tag_add?loves=0&search=' . $sf_params->get('search')) ?></span>
</div>
<br />
<?php echo form_error('search'); ?>
dediğinizden yok ama, bunlar var:
<ul id="related-search">
<?php foreach ( $sounds as $sound ) { ?>
  <li><?php echo link_to($sound['tag'], '@tag?stripped_tag=' . $sound['stripped_tag']) ?></li>
<?php } ?>
</ul>
<br />
@TODO<br />
-search yaptığın şeyi get ile ekliyorsun, misal tag/add/?vs vs. bunu postla yapsan daha mantıklı olur<br />
-executeAdd metodunda tag'i şak diye ekliyorsun, arama sonucundan geliyor adam ama yine de tag var mı yok mu kontrol et<br />
-tag/add/ ve tag/search var adam search diye tag eklemeye kalkarsa nolcak<br />
-komşuluk öldü mü, komşuluk oldu mu stripped tagleri aynı?? napcaz<br />
-boş aramayı engelle, special charackterleri engelle<br />
-search sqli çok çakma oldu, şu 21.konudaki olayı yap, kelime kelime arasın... senin ki did you mean? gibi bişe oldu<br />
-arama yaptıktan sonra seviyorum dedim, üye girişi sayfası geldi(üye girişi yapmamıştım), üye girişinden sonra 404'e yönlendi sayfa...<br />
-büyük küçük harf ile tag ekleniyor mesela 12 DeV AdAm diye bişey eklenememesi lazım.<br />