<?php
// auto-generated by sfPropelCrud
// date: 2009/01/01 18:26:05

use_helper('Date', 'Validation');
?>
<ul class="breadcrumb">
  <li class="first"><?php echo link_to('Ana Sayfa', '@homepage') ?>::</li>
  <li><a href="#">Arama</a></li>
</ul>

<div id="welcome" class="clearfix">
  <div class="tag-flash">
    <h1 class="tag"><a href="#"><?php echo $search ?></a></h1>
      <div class="love-buttons-wrap">
        <ul class="love-buttons">
          <li class="love"><?php echo link_to('Seviyor musun?', '@tag_add?sense=seviyorum&search=' . $search) ?></li>
          <li class="hate"><?php echo link_to('Sevmiyor musun?', '@tag_add?sense=sevmiyorum&search=' . $search) ?></li>
        </ul>
      </div>
      <div class="notice">
        <div class="success">
          <?php echo 'Bu etiket henüz eklenmemiş, bu etiketi profiline yukarıdaki seviyor musun veya sevmiyor musun bağlantılarına tıklayarak ekleyebilirsin. Sadece yorum yapmak için ' . link_to('buraya', '@tag_add?search=' . $search . '&sense=', 'class=bold') . ' tıklayın.' ?>
        </div>      
      </div>
  </div>

  <?php include_partial('tag/ad') ?>
</div>

<?php if ( $sounds ) { ?>
<div class="sounds-like">
  <h2 class="love">Aradığınız bu olabilir mi?</h1>
  <ul class="tag-list">
  <?php foreach ( $sounds as $sound ) { ?>
    <li><?php echo link_to($sound['tag'], '@tag?stripped_tag=' . $sound['stripped_tag'] . '&page=') ?></li>
  <?php } ?>
  </ul>
</div>
<?php } ?>

